# ?? ???? ?? ?? (user-service)
server:
  port: 8086

# ?? ???? ?? ??
spring:
  application:
    name: auth-user-service

# eureka ?? (eureka ??? ??)
eureka:
  client:
    # eureka ??? ???? ??
    register-with-eureka: true
    # eureka ??? ?? ?????? ??? ??? ??? ???? ??
    fetch-registry: true
    # eureka ?? ??? ??????? ?? ??
    service-url:
      defaultZone: http://admin:1234mst@localhost:8761/eureka

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  access:
    expiration: 1800000
    header: Authorization

  refresh:
    expiration: 259200000

    header: Authorization-Refresh