# ?? ???? ?? ?? (user-service)
server:
  port: 8083

# ?? ???? ?? ??
spring:
  application:
    name: order-fulfillment-service

# eureka ?? (eureka ??? ??)
eureka:
  client:
    # eureka ??? ???? ??
    register-with-eureka: true
    # eureka ??? ?? ?????? ??? ??? ??? ???? ??
    fetch-registry: true
    # eureka ?? ??? ??????? ?? ??
    service-url:
      defaultZone: http://admin:1234mst@localhost:8761/eureka

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}